variable "name" {
  description = "Name of the IAM Role."
}

variable "path" {
  description = "Path to the IAM Role."
  default     = "/"
}

variable "description" {
  description = "Description of the IAM Role."
  default     = "This IAM Role generated by Terraform."
}

variable "force_detach_policies" {
  description = "Detach the policy of the role."
  default     = false
}

variable "policy_arn" {
  description = "Attache the policies to the IAM Role."
  type        = list(string)
}

variable "identifiers" {
  type    = string
  default = "ec2.amazonaws.com"
}
