name: TFLint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: terraform-linters/tflint-load-config-action@v0
        with:
          source-repo: me/tflint-config
      - uses: terraform-linters/setup-tflint@v1
      - run: tflint --format compact